# Generated by Django 4.2.7 on 2025-11-03 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('optimized_route', models.JSONField(default=dict)),
                ('estimated_time', models.DurationField()),
                ('estimated_fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ai_confidence', models.FloatField(default=0.8)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule_optimizations',
            },
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('scheduling', 'Schedule Assistant'), ('analytics', 'Analytics Query'), ('support', 'Customer Support'), ('optimization', 'Route Optimization')], max_length=20)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
